---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MileHighGuy.
--- DateTime: 3/29/2023 7:58 PM
---
print("DEBUG: loaded custom_gc_6.lua")

ScriptCB_DoFile("game_testscript")
ScriptCB_DoFile("crs_instant_option_override")

